int nbSegment(int n);
int rechVal(int tab[],int n,int val);
int rechProche(int tan[],int n,int val,int *pos);
int rechMax(int tab[],int n);
int teststrlen(char mot[]);
void copie(char mot2[],char mot1[]);
void concat(char mot1[],char mot2[],char mot3[]);
int comparaison(char mot1[],char mot2[]);
int baguenaudier(int *tab,int n,int *i,int *j);
void test(void);