void afficheMenu(void);
void menuMatieres(void);
int chargement(int tabM[],int tabC[],int tailletab);
void affmat(int tabM[],int tabC[],int nbmat);
int recherche(int tabM[],int nbmat,int val);
void modif(int tabM[], int tabC[],int nbmat);
void save(int tabM[], int tabC[],int nbmat);
int newmat(int tabM[],int tabC[],int nbmat,int tailletab);
int suppr(int tabM[],int tabC[],int nbmat);
void decaler(int tab[],int pos,int nbmat);
void moyenneN(int tabM[],int nbmat);
